export const PLATFORM_USERS_COPY = {
  search: "Cari nama, username, atau email", searchHint: "Pencarian memeriksa halaman akun yang sudah dimuat. Muat lebih banyak untuk memeriksa akun lainnya.",
  list: "Daftar pengguna", identity: "Pengguna", email: "Email", communities: "Komunitas", learning: "Status belajar", reads: "Bacaan anggota-hari", completed: "Materi selesai", badges: "Lencana", quizzes: "Percobaan kuis", latest: "Belajar terakhir", location: "Lokasi perkiraan", source: "Sumber kunjungan",
  noActivity: "Belum tercatat", unknown: "Tidak tersedia", noProfile: "Profil belum dibuat", platformAdmin: "Admin platform", normalUser: "Pengguna", unknownRole: "Peran belum diketahui", role: "Peran", joined: "Bergabung", accountCreated: "Akun dibuat", accountId: "ID akun", username: "Username",
  notStarted: "Belum belajar", unknownLearning: "Belum diketahui", learningNow: "Belajar", hasBadge: "Memiliki lencana", complete: "Lengkap", partial: "Sebagian", coverage: "Cakupan data",
  loading: "Memuat pengguna…", loadingMore: "Memuat akun berikutnya…", more: "Muat lebih banyak", exhausted: "Seluruh akun sudah diperiksa.", rows: "akun ditampilkan", empty: "Tidak ada pengguna yang cocok pada halaman yang sudah dimuat.",
  scroll: "Geser tabel ke samping untuk melihat kolom lainnya.", view: "Lihat aktivitas", export: "Unduh akun yang ditampilkan", error: "Data pengguna gagal dimuat. Periksa koneksi lalu coba lagi.", denied: "Data pengguna hanya tersedia untuk admin platform.", retry: "Coba lagi",
  capped: "Sebagian sumber mencapai batas pembacaan. Angka ≥ adalah jumlah minimum. Progres kelas yang belum lengkap tidak ditampilkan sebagai persentase pasti.",
  profile: "Identitas akun", currentMemberships: "Keanggotaan saat ini", courses: "Progres per kelas", course: "Kelas", progress: "Progres materi", percent: "Persentase", status: "Status", notCompleted: "Belum tuntas", completedCourse: "Tuntas", badgeEarned: "Lencana tercatat", noBadge: "Belum ada lencana", noCommunities: "Belum bergabung dalam komunitas.", noCourses: "Belum ada kelas yang dapat ditampilkan.",
  courseHint: "Progres memakai materi published yang memenuhi syarat pada kelas saat ini. Lencana adalah catatan penyelesaian yang pernah diraih, bukan jaminan seluruh materi terbaru telah dituntaskan.",
  reading: "Bacaan terbaru", material: "Materi", date: "Waktu (WIB)", noReads: "Belum ada bacaan anggota yang tercatat.", quizResults: "Hasil kuis terbaru", quiz: "Kuis", score: "Nilai", result: "Hasil", passed: "Lulus", failed: "Belum lulus", noQuizzes: "Belum ada percobaan kuis.",
  traffic: "Kunjungan dan klik tautan", from: "Halaman asal", target: "Tujuan tautan", referrer: "Situs perujuk", campaign: "Campaign", device: "Perangkat", browser: "Browser / OS", kind: "Aktivitas", page: "Kunjungan halaman", click: "Klik tautan", directOrUnknown: "Langsung / tidak tercatat", noVisits: "Belum ada kunjungan atau klik yang terhubung ke akun ini.",
  trackingNote: "Aktivitas akun direkam saat pengguna login sejak fitur ini tersedia. Sesi pengunjung anonim yang lama tidak dihubungkan ke identitas akun; lokasi dan sumber lama tetap tidak tersedia.",
  geoNote: "Lokasi berasal dari GeoIP lokal dan bersifat perkiraan; bukan GPS atau alamat pasti. Negara/kota yang tidak diketahui tetap ditampilkan sebagai tidak tersedia.", geoAttribution: "IP Geolocation by DB-IP", privacy: "Definisi data dan privasi", privacyNote: "IP mentah tidak disimpan. Klik mencatat halaman asal dan tujuan yang sudah dibersihkan dari query; tidak merekam isi materi, jawaban kuis, atau token. Timeline hanya mencakup aktivitas akun yang masih dalam retensi 30 hari; DNT/GPC dapat membatasi pencatatan.",
  recentLimit: "Daftar bacaan, kuis, dan timeline menampilkan aktivitas terbaru dengan pembacaan terbatas.", noUser: "Akun tidak ditemukan.",
} as const;
export type PlatformUsersCopy = { [K in keyof typeof PLATFORM_USERS_COPY]: string };
export type PlatformUsersCopyOverride = Partial<PlatformUsersCopy>;
export const mergePlatformUsersCopy = (copy?: PlatformUsersCopyOverride): PlatformUsersCopy => ({ ...PLATFORM_USERS_COPY, ...copy });
